### ISSUE TITLE
Error with n_rec >= 18

### ISSUE THREAD

**Issue by sjcotto** [massquantity/LibRecommender#152]
hi there, 

```
LibRecommender==0.10.2
```

I'm using the SVD model

```
data_info = DataInfo.load("./" + index, model_name="model")
    # load model, should specify the model name, e.g., DeepFM
    model = SVDpp.load(path="./" + index, model_name="model",
                        data_info=data_info, manual=True)
```

For inference

```
res = model.recommend_user(user=item.user, n_rec=item.n)
```
I don't have any issues if item.n is <= 17, but for 18 or bigger numbers I'm getting the following error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None

```

**Comment by massquantity** [comment]
Does this happen to all the user or just one user?

**Comment by sjcotto** [comment]
hi, it happens to most users but it doesn't happen to a non-user, like user_id = -1

this can be related to the embed_size ? if so, what would be the way to know that value?

**Comment by massquantity** [comment]
The model will filter out items that a user has previously consumed before recommending. So I'm guessing some users may have consumed a lot of items, and setting a high `n_rec` value will make the model have no item to recommend, which led to the error. But I can't be sure before seeing the error trace from LibRecommender.
I'm also considering adding an option that users can choose whether to filter consumed items.

**Comment by sjcotto** [comment]
it's possible to change the behaviour to not return an error in that scenario? I think returning a lower number of items or the already consumed ones is best than the unexpected error, wdyt?

**Comment by massquantity** [comment]
Yes it is possible and a much more elegant way for recommendations. But again I'm not sure this is your error's cause. If one sets a relatively large `n_rec`, the error will look like this
```
  File "/home/Workspace/LibRecommender/libreco/recommendation/recommend.py", line 30, in rank_recommendations
    ids = np.argpartition(recos, -count)[-count:]
  File "<__array_function__ internals>", line 5, in argpartition
  File "/home/miniconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 832, in argpartition
    return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
  File "/home/miniconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: kth(=-26375) out of bounds (3667)

```

**Comment by sjcotto** [comment]
ok, maybe is a different one, here is the complete code: 

kind of same as in repo examples

```
data = pd.read_csv(item.uri, sep=",", header=0,names=["user", "item", "label", "time"])
    
    tf.compat.v1.reset_default_graph()

    # split whole data into three folds for training, evaluating and testing
    train_data, eval_data, test_data = random_split(data, multi_ratios=[0.8, 0.1, 0.1])

    train_data, data_info = DatasetPure.build_trainset(train_data)
    eval_data = DatasetPure.build_evalset(eval_data)
    test_data = DatasetPure.build_testset(test_data)
    print(data_info)   # n_users: 5894, n_items: 3253, data sparsity: 0.4172 %

    svdpp = SVDpp(task="rating", data_info=data_info, embed_size=32, n_epochs=20, lr=0.001,
                reg=None, batch_size=256)
    # monitor metrics on eval_data during training
    
    svdpp.fit(train_data, verbose=2, eval_data=eval_data, metrics=["rmse", "mae", "r2"])

    # do final evaluation on test data
    print("evaluate_result: ", evaluate(model=svdpp, data=test_data,
                                        metrics=["rmse", "mae"]))

    print("recommendation: ", svdpp.recommend_user(user=181791, n_rec=50))
```

using
```
LibRecommender==0.10.2
```

tried with different embed_size (16,32) but I still have the error not always with the same `n_rec` - so, it's associated with embed_size but not sure. 

do you have any ideas or things to try?

**Comment by massquantity** [comment]
If it's the embed_size, maybe the cause is memory limitation in your sever. Can you get the error trace directly from LibRecommender? I can't find any line linked to LibRecommender from your previous error trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
```
