### ISSUE TITLE
Training Tensorflow 1.15  Model on Multi-GPUs on AWS using MirroredStrategy()

### ISSUE THREAD

**Issue by Shadz13** [massquantity/LibRecommender#29]
To create distribute training over multiple GPUs, I am using MirroredStrategy() from the tensorflow library. The code is as follows:
```
             n_gpus = len(devices_names)
             print('The number of device :',n_gpus)
             if n_gpus>0:
                 mirrored_strategy = tf.distribute.MirroredStrategy(devices=devices_names[:n_gpus])
                 
                 with mirrored_strategy.scope():
                     ytb_ranking = YouTubeRanking(task="ranking", data_info=data_info,
                                                       embed_size=24, n_epochs=17, lr=1e-5, #0.01
                                                       batch_size=150, use_bn=True, #batch_size=512 hidden_units="128,64,32"
                                                       hidden_units="128,64,32")
             else :  
                 ytb_ranking = YouTubeRanking(task="ranking", data_info=data_info,
                                                       embed_size=24, n_epochs=17, lr=1e-5, #0.01
                                                       batch_size=150, use_bn=True, #batch_size=512 hidden_units="128,64,32"
                                                       hidden_units="128,64,32")
            
             ytb_ranking.fit(train_data, verbose=2, shuffle=True,
                                     eval_data=test_data,
                                     metrics=["loss", "roc_auc", "precision","recall"
                                              , "map", "ndcg"])
```
![GPu4](https://user-images.githubusercontent.com/42578613/100917004-3ff05b00-34df-11eb-9b70-41d08c5e5be4.PNG)

The Instance Type: g3.16xlarge
GPUs: 4
GPU Memory (GiB):32

Using watch "nividia-smi", I am able to view the usage as shown below:
![gpu3](https://user-images.githubusercontent.com/42578613/100917193-804fd900-34df-11eb-9ee7-ae142fa97d3e.PNG)
The issue is that the processing is only occurring on one of the GPU and the rest seems idle. How can I rectify this, such that all GPUs are used equally?

**Comment by massquantity** [comment]
First of all, I don't have multiple GPUs and renting a multi-GPUs instance on AWS costs too much for me, so I can only make my best guesses.
The most possible cause lies in the data input process. According to the [tf doc](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/distribute), they use `Data parallelism`, so the feeding dataflow should be split into multiple GPUs too.
To do that one should modify the `fit()` function, which is complicated, and I don't know the correct answer.

Another possible cause is the models in this library are mainly implemented in tf1, and as you know Google mainly supports tf2 now. So MirroredStrategy may not be compatible with tf1. 

Recently I am seriously considering transfering all the models to tf2 implementation. In this way we can leverage the new `Dataset` API to do efficient data input pipeline, which may eventually make training on multi-GPUs feasible.

**Comment by massquantity** [comment]
By the way, I just found an official TensorFlow [recommender library](https://github.com/tensorflow/recommenders). Maybe you can try some luck on that :)

**Comment by Shadz13** [comment]
https://github.com/tensorflow/tensorflow/issues/38889#issuecomment-620945475

I came across this link and using the it as guideline to resolve the issue.

**Comment by massquantity** [comment]
Have you solved it? It seems that the choice is either using tf2 or Estimator API.

**Comment by Shadz13** [comment]
I will have to setup the test on my PC, since I am still running the scripts on the AWS instance. I will try out the Estimator API and post the updates in detail. 

This can also be a solution for me to upgrade to tensorflow v2 https://www.tensorflow.org/guide/upgrade.

**Comment by Shadz13** [comment]
I am using the following link as a guideline https://medium.com/tensorflow/multi-gpu-training-with-estimators-tf-keras-and-tf-data-ba584c3134db . In this link, there is a example notebook. 
According to the tutorial, the steps for creating an estimator is the following:
```
NUM_GPUS = 2strategy = tf.contrib.distribute.MirroredStrategy(num_gpus=NUM_GPUS)
config = tf.estimator.RunConfig(train_distribute=strategy)estimator = tf.keras.estimator.model_to_estimator(model,
                                                  config=config)
```
The next step is to create an input function for the estimate so that the dataset is distributed. The final steps is to train the estimator and output the performance.

Below is the revised code for librecommender. I am currently just trying to create the estimator.
```
import numpy as np
import pandas as pd
import os
import sys

file_dir = os.path.dirname("C:\\Projects\\Recommendation\\LibRecommender\\LibRecommender\\")
sys.path.append(file_dir)

from libreco.data import split_by_ratio_chrono, DatasetFeat
from libreco.algorithms import YouTubeRanking

# remove unnecessary tensorflow logging
import os
import tensorflow as tf
 ####add
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ["KMP_WARNINGS"] = "FALSE"
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession
import time
#config = ConfigProto()
#config.gpu_options.allow_growth = True
#session = InteractiveSession(config=config)

config = ConfigProto()
config.gpu_options.allow_growth = True
config.log_device_placement = True
sess = tf.Session(config=config)

os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'
 ####add
if __name__ == "__main__":
    data = pd.read_csv("sample_data/sample_movielens_merged.csv",
                       sep=",", header=0)
    # convert to implicit data and do negative sampling afterwards
    data["label"] = 1

    # split into train and test data based on time
    train_data, test_data = split_by_ratio_chrono(data, test_size=0.2)

    # specify complete columns information
    sparse_col = ["sex", "occupation", "genre1", "genre2", "genre3"]
    dense_col = ["age"]
    user_col = ["sex", "age", "occupation"]
    item_col = ["genre1", "genre2", "genre3"]

    train_data, data_info = DatasetFeat.build_trainset(
        train_data, user_col, item_col, sparse_col, dense_col)
    test_data = DatasetFeat.build_testset(test_data, sparse_col, dense_col)

    # sample negative items for each record
    train_data.build_negative_samples(data_info)
    test_data.build_negative_samples(data_info)
    print(data_info)  # n_users: 5962, n_items: 3226, data sparsity: 0.4185 %
    tf.reset_default_graph()      ####add
    ytb_ranking = YouTubeRanking(task="ranking", data_info=data_info,
                                 embed_size=16, n_epochs=3, lr=1e-4,
                                 batch_size=512, use_bn=True,
                                 hidden_units="128,64,32")
    NUM_GPUS = 2

    strategy = tf.contrib.distribute.MirroredStrategy(num_gpus=NUM_GPUS,cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())
    config = tf.estimator.RunConfig(train_distribute=strategy)
```
I obtained the following error :  

```
runfile('C:/Projects/Recommendation/LibRecommender/LibRecommender/examples/feat_exampleMultiGPU.py', wdir='C:/Projects/Recommendation/LibRecommender/LibRecommender/examples')

2020-12-12 13:42:09.547438: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-12-12 13:42:12,125 - WARNING - Similarity cython version is not available
2020-12-12 13:42:12,134 - WARNING - Als cython version is not available
2020-12-12 13:42:12,136 - WARNING - BPR cython version is not available

2020-12-12 13:42:09.547438: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-12-12 13:42:12.152558: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-12-12 13:42:12.155265: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-12-12 13:42:12.485567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:09:00.0
2020-12-12 13:42:12.485748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0a:00.0
2020-12-12 13:42:12.485770: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll

2020-12-12 13:42:09.547438: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-12-12 13:42:12.152558: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-12-12 13:42:12.155265: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-12-12 13:42:12.485567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:09:00.0
2020-12-12 13:42:12.485748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0a:00.0
2020-12-12 13:42:12.485770: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-12-12 13:42:12.749001: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-12-12 13:42:12.998313: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-12-12 13:42:13.025427: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-12-12 13:42:13.301659: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll

2020-12-12 13:42:09.547438: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-12-12 13:42:12.152558: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-12-12 13:42:12.155265: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-12-12 13:42:12.485567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:09:00.0
2020-12-12 13:42:12.485748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0a:00.0
2020-12-12 13:42:12.485770: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-12-12 13:42:12.749001: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-12-12 13:42:12.998313: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-12-12 13:42:13.025427: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-12-12 13:42:13.301659: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-12-12 13:42:13.560522: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-12-12 13:42:13.845170: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-12-12 13:42:13.845703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:09:00.0, compute capability: 6.1
/job:localhost/replica:0/task:0/device:GPU:1 -> device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:0a:00.0, compute capability: 6.1

Non_train_data 1 size before filtering: 19535

2020-12-12 13:42:09.547438: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-12-12 13:42:12.152558: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-12-12 13:42:12.155265: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-12-12 13:42:12.485567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:09:00.0
2020-12-12 13:42:12.485748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0a:00.0
2020-12-12 13:42:12.485770: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-12-12 13:42:12.749001: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-12-12 13:42:12.998313: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-12-12 13:42:13.025427: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-12-12 13:42:13.301659: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-12-12 13:42:13.560522: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-12-12 13:42:13.845170: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-12-12 13:42:13.845703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
2020-12-12 13:42:15.186946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-12 13:42:15.186979: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1 
2020-12-12 13:42:15.186986: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N Y 
2020-12-12 13:42:15.186992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   Y N 
2020-12-12 13:42:15.188179: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9549 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:09:00.0, compute capability: 6.1)
2020-12-12 13:42:15.189392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 9549 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:0a:00.0, compute capability: 6.1)
Non_train_data 1 size after filtering: 19535
random neg item sampling elapsed: 0.084s
random neg item sampling elapsed: 0.020s
n_users: 5962, n_items: 3226, data sparsity: 0.4185 %

2020-12-12 13:42:09.547438: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-12-12 13:42:12.152558: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-12-12 13:42:12.155265: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-12-12 13:42:12.485567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:09:00.0
2020-12-12 13:42:12.485748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0a:00.0
2020-12-12 13:42:12.485770: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-12-12 13:42:12.749001: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-12-12 13:42:12.998313: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-12-12 13:42:13.025427: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-12-12 13:42:13.301659: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-12-12 13:42:13.560522: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-12-12 13:42:13.845170: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-12-12 13:42:13.845703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
2020-12-12 13:42:15.186946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-12 13:42:15.186979: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1 
2020-12-12 13:42:15.186986: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N Y 
2020-12-12 13:42:15.186992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   Y N 
2020-12-12 13:42:15.188179: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9549 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:09:00.0, compute capability: 6.1)
2020-12-12 13:42:15.189392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 9549 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:0a:00.0, compute capability: 6.1)
2020-12-12 13:42:15.974380: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:09:00.0
2020-12-12 13:42:15.974428: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0a:00.0
2020-12-12 13:42:15.974442: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-12-12 13:42:15.974452: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-12-12 13:42:15.974461: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-12-12 13:42:15.974469: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-12-12 13:42:15.974478: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-12-12 13:42:15.974562: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-12-12 13:42:15.974575: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-12-12 13:42:15.974631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
2020-12-12 13:42:15.974717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-12 13:42:15.974725: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1 
2020-12-12 13:42:15.974730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N Y 
2020-12-12 13:42:15.974736: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   Y N 
2020-12-12 13:42:15.974828: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9549 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:09:00.0, compute capability: 6.1)
2020-12-12 13:42:15.974870: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 9549 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:0a:00.0, compute capability: 6.1)
Traceback (most recent call last):

  File "C:\Users\NN\.conda\envs\2020\lib\inspect.py", line 1126, in getfullargspec
    sigcls=Signature)

  File "C:\Users\NN\.conda\envs\2020\lib\inspect.py", line 2193, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))

TypeError: <libreco.algorithms.youtube_ranking.YouTubeRanking object at 0x00000238327E89E8> is not a callable object


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Projects\Recommendation\LibRecommender\LibRecommender\examples\feat_exampleMultiGPU.py", line 66, in <module>
    estimator = tf.estimator.Estimator(ytb_ranking, config=config)

  File "C:\Users\NN\.conda\envs\2020\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 219, in __init__
    model_fn_lib.verify_model_fn_args(model_fn, params)

  File "C:\Users\NN\.conda\envs\2020\lib\site-packages\tensorflow_estimator\python\estimator\model_fn.py", line 620, in verify_model_fn_args
    args = set(function_utils.fn_args(model_fn))

  File "C:\Users\NN\.conda\envs\2020\lib\site-packages\tensorflow_core\python\util\function_utils.py", line 57, in fn_args
    args = tf_inspect.getfullargspec(fn).args

  File "C:\Users\NN\.conda\envs\2020\lib\site-packages\tensorflow_core\python\util\tf_inspect.py", line 257, in getfullargspec
    return _getfullargspec(target)

  File "C:\Users\NN\.conda\envs\2020\lib\inspect.py", line 1132, in getfullargspec
    raise TypeError('unsupported callable') from ex

TypeError: unsupported callable
```

Due to the error, should the estimator be created class at line 213 and 214.
```
        self._build_model()
        self._build_train_ops(global_steps)
```

**Comment by massquantity** [comment]
Hmm... This concludes that `LibRecommender` can't leverage multi-GPUs right now :) 
Even if you can successfully use multi-GPUs to train the model in the library, I doubt that it will bring a big acceleration. Because the data pipeline was not optimized for multi-GPUs, and CPUs are likely to become a bottleneck when processing data.

**Comment by apdullahyayik** [comment]
#70 Check out my solution for Multi-GPU implementation
