### ISSUE TITLE
Error in saving model

### ISSUE THREAD

**Issue by SohumBhatt** [massquantity/LibRecommender#78]
I've had some trouble trying to save my TF based model for serving. Each time I try to save it, it fails to save due to the inability to find a temporary file? I've tried limiting the path size, and using the absolute path. I've copied the code and error below, and apologies in advance if I've made a simple mistake somewhere!

```python
dinr = DIN('ranking', info)
dinr.fit(train)

path = r'C:\Users\xxxx\Documents\RecSysOnlineDev\di' 
save_info(path, dinr, train, info) 
save_model_tf_serving(path, dinr, "din") 
```

```
WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\libreco\utils\serialization.py:199: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
2021-11-04 11:19:51.859757: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: Failed to create a NewWriteableFile: C:\Users\xxx\Documents\RecSysOnlineDev\di\din/1\variables\variables_temp\part-00000-of-00001.data-00000-of-00001.tempstate16195143275829308955 : The system cannot find the path specified.
; No such process
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: C:\Users\xxxx\Documents\RecSysOnlineDev\di\din/1\variables\variables_temp\part-00000-of-00001.data-00000-of-00001.tempstate16195143275829308955 : The system cannot find the path specified.
; No such process
	 [[{{node save/SaveV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/xxxx/Documents/RecSysOnlineDev/RecSysTrainAndSave.py", line 29, in <module>
    save_model_tf_serving(path, dinr, "din")  # save tf model
  File "C:\ProgramData\Anaconda3\lib\site-packages\libreco\utils\serialization.py", line 232, in save_model_tf_serving
    builder.add_meta_graph_and_variables(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 535, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\saved_model\builder_impl.py", line 596, in add_meta_graph_and_variables
    saver.save(sess, variables_path, write_meta_graph=False, write_state=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1207, in save
    raise exc
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1188, in save
    model_checkpoint_path = sess.run(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: C:\Users\xxxx\Documents\RecSysOnlineDev\di\din/1\variables\variables_temp\part-00000-of-00001.data-00000-of-00001.tempstate16195143275829308955 : The system cannot find the path specified.
; No such process
	 [[node save/SaveV2 (defined at \ProgramData\Anaconda3\lib\site-packages\libreco\utils\serialization.py:232) ]]

Errors may have originated from an input operation.
Input Source operations connected to node save/SaveV2:
 dense/kernel (defined at \ProgramData\Anaconda3\lib\site-packages\libreco\algorithms\din.py:332)	
 sparse_feat (defined at \ProgramData\Anaconda3\lib\site-packages\libreco\algorithms\din.py:175)	
 mlp/batch_normalization/beta/Adam_1 (defined at \ProgramData\Anaconda3\lib\site-packages\libreco\algorithms\din.py:376)	
 mlp/batch_normalization_2/moving_variance (defined at \ProgramData\Anaconda3\lib\site-packages\libreco\utils\tf_ops.py:34)	
 mlp/mlp_layer2/bias (defined at \ProgramData\Anaconda3\lib\site-packages\libreco\utils\tf_ops.py:26)	
 mlp/batch_normalization/moving_mean (defined at \ProgramData\Anaconda3\lib\site-packages\libreco\utils\tf_ops.py:23)	
 user_feat (defined at \ProgramData\Anaconda3\lib\site-packages\libreco\algorithms\din.py:164)	
 dense_feat (defined at \ProgramData\Anaconda3\lib\site-packages\libreco\algorithms\din.py:181)	
 dense_1/bias (defined at \ProgramData\Anaconda3\lib\site-packages\libreco\algorithms\din.py:144)	
 item_feat (defined at \ProgramData\Anaconda3\lib\site-packages\libreco\algorithms\din.py:169)

Original stack trace for 'save/SaveV2':
  File "/Users/xxxx/Documents/RecSysOnlineDev/RecSysTrainAndSave.py", line 29, in <module>
    save_model_tf_serving(path, dinr, "din")  # save tf model
  File "\ProgramData\Anaconda3\lib\site-packages\libreco\utils\serialization.py", line 232, in save_model_tf_serving
    builder.add_meta_graph_and_variables(
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 535, in new_func
    return func(*args, **kwargs)
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\saved_model\builder_impl.py", line 590, in add_meta_graph_and_variables
    saver = self._maybe_create_saver(saver)
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\saved_model\builder_impl.py", line 223, in _maybe_create_saver
    saver = tf_saver.Saver(
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 836, in __init__
    self.build()
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 848, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 876, in _build
    self.saver_def = self._builder._build_internal(  # pylint: disable=protected-access
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 507, in _build_internal
    save_tensor = self._AddShardedSaveOps(filename_tensor, per_device)
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 299, in _AddShardedSaveOps
    return self._AddShardedSaveOpsForV2(filename_tensor, per_device)
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 273, in _AddShardedSaveOpsForV2
    sharded_saves.append(self._AddSaveOps(sharded_filename, saveables))
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 205, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 120, in save_op
    return io_ops.save_v2(filename_tensor, tensor_names, tensor_slices,
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1701, in save_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
```

**Comment by massquantity** [comment]
Yeah sorry it's a bug. The complete path generated is `C:\Users\xxxx\Documents\RecSysOnlineDev\di\din/1\variables\variables_temp`, and it has a '/' in front of 1, which is not compatible in Windows. If you look at the code in line 152 of [serialization.py](https://github.com/massquantity/LibRecommender/blob/master/libreco/utils/serialization.py#L152): 
```python
export_path = os.path.join(path, f"{model_name}/{version}")
```
which should be 
```python
export_path = os.path.join(path, f"{model_name}", f"{version}")
```
I'll fix it recently, or you can change the source code by yourself.

**Comment by SohumBhatt** [comment]
Huh, yeah, that did strike me as odd. Thanks for the quick response!
