### ISSUE TITLE
ValueError: all the input array dimensions except for the concatenation axis must match exactly

### ISSUE THREAD

**Issue by Kribashnee** [massquantity/LibRecommender#8]
Hi Everyone,

Version : LibRecommender=0.1.0
Dataset Format: user item label time ProdHouse clientGender ClientAge  childDepInd
![data1](https://user-images.githubusercontent.com/42578613/94990011-25e6da80-0579-11eb-8357-d03225c82f74.PNG)

```
user               int64
item               int64
label              int64
time               int64
ProdHouse          int32
clientGender       int32
ClientAge        float64
Child_Dep_Ind      int64
dtype: object
```

I have the set following:
```
    # split into train and test data based on time
    train_data, test_data = split_by_ratio_chrono(data, test_size=0.2)
    
    # specify complete columns information
    sparse_col = ["ClientAge"] 
    dense_col = ["ProdHouse","Child_Dep_Ind","clientGender"]
    user_col = ["clientGender","ClientAge","Child_Dep_Ind"]
    item_col = ["ProdHouse"]
```

I get the following error when trying to run youtube recommender model on my own dataset:
```
Traceback (most recent call last):

  File "C:\Projects\RecommendationModel\LibRecommender-master\LibRec\main\momentum_feat_main.py", line 117, in <module>
    "recall", "map", "ndcg"])

  File "C:\Anaconda3\envs\Rec\lib\site-packages\librecommender-0.1.0-py3.6-win-amd64.egg\libreco\algorithms\youtube_ranking.py", line 244, in fit
    self.print_metrics(eval_data=eval_data, metrics=metrics)

  File "C:\Anaconda3\envs\Rec\lib\site-packages\librecommender-0.1.0-py3.6-win-amd64.egg\libreco\evaluate\evaluate.py", line 145, in print_metrics
    self, chosen_users, k)

  File "C:\Anaconda3\envs\Rec\lib\site-packages\librecommender-0.1.0-py3.6-win-amd64.egg\libreco\evaluate\evaluate.py", line 185, in compute_recommends
    reco = model.recommend_user(u, k)

  File "C:\Anaconda3\envs\Rec\lib\site-packages\librecommender-0.1.0-py3.6-win-amd64.egg\libreco\algorithms\youtube_ranking.py", line 286, in recommend_user
    self.data_info, user, self.n_items, self.sparse, self.dense)

  File "C:\Anaconda3\envs\Rec\lib\site-packages\librecommender-0.1.0-py3.6-win-amd64.egg\libreco\utils\unique_features.py", line 73, in get_recommend_indices_and_values
    data_info, user, n_items=n_items, mode="recommend") if dense else None

  File "C:\Anaconda3\envs\Rec\lib\site-packages\librecommender-0.1.0-py3.6-win-amd64.egg\libreco\utils\unique_features.py", line 152, in get_dense_values
    [user_dense_part, item_dense_part], axis=-1)[:, col_reindex]

ValueError: all the input array dimensions except for the concatenation axis must match exactly
```

This occurs at the following line:
```
    elif mode == "recommend":
        if user_dense_col and item_dense_col:
            user_dense_part = np.tile(data_info.user_dense_unique[user],
                                      (n_items, 1))
            item_dense_part = data_info.item_dense_unique
            print(item_dense_part.shape)
            print(user_dense_part.shape)
            dense_values = np.concatenate(
                [user_dense_part, item_dense_part], axis=-1)[:, col_reindex]
            return dense_values
        elif user_dense_col:
            return np.tile(data_info.user_dense_unique[user], (n_items, 1))
        elif item_dense_col:
            return data_info.item_dense_unique
```

I have added a print statement to the code as seen above and the output is (57, 1) and (54, 2). There is a mismatch but I have one dataset which is split into a training and test set. I am not sure how to fix this, can you kindly assist or guide me in rectifying the error?

**Comment by massquantity** [comment]
Well this is odd, based on the information you provided, there are 57 unique items in `data_info.item_dense_unique` and 54 unique items in `n_items` . So how many unique items actually in the original dataset ?

**Comment by massquantity** [comment]
I figured out one possible reason. According to your data, item has a dense feature `ProdHouse`, but maybe some items don't have a unique `ProdHouse` value. For example, in one sample item 1's ProdHouse is 1, then in another sample item 1's ProdHouse is 0. This will cause the `data_info.item_dense_unique` has larger dim than `n_items`.

**Comment by Kribashnee** [comment]
When I set the following:
    # specify complete columns information
    sparse_col = ["clientGender","Child_Dep_Ind","ProdHouse","ClientAge"] 
    dense_col = []
    user_col = ["clientGender","ClientAge","Child_Dep_Ind","ProdHouse"]
    item_col = []
It does train and output results. If ProdHouse has nulls would this also affect it?
